// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArpoE2v7tNGnrdWvEFxQ15VE5P2WkpgrQ',
    appId: '1:727923135750:web:eed89d7ec1373f1fb4fa87',
    messagingSenderId: '727923135750',
    projectId: 'fruite-hub-52443',
    authDomain: 'fruite-hub-52443.firebaseapp.com',
    storageBucket: 'fruite-hub-52443.firebasestorage.app',
    measurementId: 'G-TPKKDFGYVK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAz3erjSq81-NoDOBaMgIbW0YVpS5lvjh4',
    appId: '1:727923135750:android:a393756e19e534b9b4fa87',
    messagingSenderId: '727923135750',
    projectId: 'fruite-hub-52443',
    storageBucket: 'fruite-hub-52443.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqYcgCA8t4UiYDQFXydM6ExOLLA00Z7io',
    appId: '1:727923135750:ios:16a1f6027a3ad9f1b4fa87',
    messagingSenderId: '727923135750',
    projectId: 'fruite-hub-52443',
    storageBucket: 'fruite-hub-52443.firebasestorage.app',
    iosClientId: '727923135750-cr8n1ek2djsi1d601u1u7euu4c1dogpa.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruiteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqYcgCA8t4UiYDQFXydM6ExOLLA00Z7io',
    appId: '1:727923135750:ios:16a1f6027a3ad9f1b4fa87',
    messagingSenderId: '727923135750',
    projectId: 'fruite-hub-52443',
    storageBucket: 'fruite-hub-52443.firebasestorage.app',
    iosClientId: '727923135750-cr8n1ek2djsi1d601u1u7euu4c1dogpa.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruiteApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArpoE2v7tNGnrdWvEFxQ15VE5P2WkpgrQ',
    appId: '1:727923135750:web:266e5aa19efb00b3b4fa87',
    messagingSenderId: '727923135750',
    projectId: 'fruite-hub-52443',
    authDomain: 'fruite-hub-52443.firebaseapp.com',
    storageBucket: 'fruite-hub-52443.firebasestorage.app',
    measurementId: 'G-4JN255PMB0',
  );

}