// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArpoE2v7tNGnrdWvEFxQ15VE5P2WkpgrQ',
    appId: '1:727923135750:web:b8dff7d8ecd5bf06b4fa87',
    messagingSenderId: '727923135750',
    projectId: 'fruite-hub-52443',
    authDomain: 'fruite-hub-52443.firebaseapp.com',
    storageBucket: 'fruite-hub-52443.firebasestorage.app',
    measurementId: 'G-3ET81JL2GH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAz3erjSq81-NoDOBaMgIbW0YVpS5lvjh4',
    appId: '1:727923135750:android:73dcaf852fa8061bb4fa87',
    messagingSenderId: '727923135750',
    projectId: 'fruite-hub-52443',
    storageBucket: 'fruite-hub-52443.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqYcgCA8t4UiYDQFXydM6ExOLLA00Z7io',
    appId: '1:727923135750:ios:689d10be9b2035dab4fa87',
    messagingSenderId: '727923135750',
    projectId: 'fruite-hub-52443',
    storageBucket: 'fruite-hub-52443.firebasestorage.app',
    iosBundleId: 'com.example.fruiteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqYcgCA8t4UiYDQFXydM6ExOLLA00Z7io',
    appId: '1:727923135750:ios:689d10be9b2035dab4fa87',
    messagingSenderId: '727923135750',
    projectId: 'fruite-hub-52443',
    storageBucket: 'fruite-hub-52443.firebasestorage.app',
    iosBundleId: 'com.example.fruiteApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArpoE2v7tNGnrdWvEFxQ15VE5P2WkpgrQ',
    appId: '1:727923135750:web:355a0332b211d5aeb4fa87',
    messagingSenderId: '727923135750',
    projectId: 'fruite-hub-52443',
    authDomain: 'fruite-hub-52443.firebaseapp.com',
    storageBucket: 'fruite-hub-52443.firebasestorage.app',
    measurementId: 'G-VPZKP6M8Z5',
  );
}
