// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5m8cbbfkIWX5-4go_J8w42mwrb6MJpkw',
    appId: '1:28237635130:web:2b355769565d03c6be5f03',
    messagingSenderId: '28237635130',
    projectId: 'fruite-app2511',
    authDomain: 'fruite-app2511.firebaseapp.com',
    storageBucket: 'fruite-app2511.firebasestorage.app',
    measurementId: 'G-PR9QJVPP8N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCga4ArFutICACovFLHK7lt-OuLxnk0xXk',
    appId: '1:28237635130:android:5f74f1cca8718d00be5f03',
    messagingSenderId: '28237635130',
    projectId: 'fruite-app2511',
    storageBucket: 'fruite-app2511.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCO6KLc8WLRUz8wMMCManne98TKoEBSQTw',
    appId: '1:28237635130:ios:48623822e9910169be5f03',
    messagingSenderId: '28237635130',
    projectId: 'fruite-app2511',
    storageBucket: 'fruite-app2511.firebasestorage.app',
    androidClientId: '28237635130-3bei7l1eqlgkjpr2tsu6uvafkr3md2a6.apps.googleusercontent.com',
    iosClientId: '28237635130-vlc4rp1mv8fg3uh7pm8baqiroq2l029p.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruiteNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCO6KLc8WLRUz8wMMCManne98TKoEBSQTw',
    appId: '1:28237635130:ios:48623822e9910169be5f03',
    messagingSenderId: '28237635130',
    projectId: 'fruite-app2511',
    storageBucket: 'fruite-app2511.firebasestorage.app',
    androidClientId: '28237635130-3bei7l1eqlgkjpr2tsu6uvafkr3md2a6.apps.googleusercontent.com',
    iosClientId: '28237635130-vlc4rp1mv8fg3uh7pm8baqiroq2l029p.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruiteNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5m8cbbfkIWX5-4go_J8w42mwrb6MJpkw',
    appId: '1:28237635130:web:974314045923c101be5f03',
    messagingSenderId: '28237635130',
    projectId: 'fruite-app2511',
    authDomain: 'fruite-app2511.firebaseapp.com',
    storageBucket: 'fruite-app2511.firebasestorage.app',
    measurementId: 'G-CCGXF69GL8',
  );
}
